# Generated by Django 4.2.4 on 2023-09-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=255)),
                ('path', models.ImageField(upload_to='imagem/site/')),
            ],
        ),
    ]
