# Generated by Django 4.2.4 on 2023-09-04 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moda', '0002_cardproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConteudoSegundoMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('path', models.ImageField(upload_to='imagem/site/')),
            ],
        ),
    ]
